spring.application.name=storage
server.port=8081

# Banco de dados PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tokseg}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialization-mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Desativa Flyway
spring.flyway.enabled=false
#spring.flyway.url=jdbc:postgresql://localhost:5432/tokseg
#spring.flyway.user=postgres
#spring.flyway.password=root
#spring.flyway.schemas=public
#logging.level.org.flywaydb=DEBUG

# JWT e MVC
api.security.token.secret=${JWT_SECREAT:tokseg-secret-key}
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Configurações serviço de email

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port= 2525
spring.mail.username=d3d96c5a906bbb
spring.mail.password=f0f2db896f7ef1
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.smtp.starttls.enable=true
