spring.application.name=storage
server.port=8081

# Configura��o do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tokseg
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura��o do Hibernate (JPA)
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/tokseg
spring.flyway.user=postgres
spring.flyway.password=tiradentes
spring.flyway.schemas=public
logging.level.org.flywaydb=DEBUG

api.security.token.secret=${JWT_SECREAT:tokseg-secret-key}
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

