
CREATE TABLE "users" (
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    telephone VARCHAR(20) NULL DEFAULT NULL,
    role VARCHAR(15) NOT NULL
);